server:
  port: 10001

spring:
  application:
    name: dot-gateway
  cloud:
    nacos:
      username: @nacos.username@
      password: @nacos.password@
      discovery:
        server-addr: ${REGISTER_SERVER:dot-register}:${REGISTER_PORT:8848}
        namespace: @nacos.namespace@
      config:
        server-addr: ${REGISTER_SERVER:dot-register}:${REGISTER_PORT:8848}
        namespace: @nacos.namespace@
  config:
    import:
      - nacos:dot-common.yml
      - optional:nacos:${spring.application.name}.yml
